kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build
    image: plugins/docker
    settings:
      username: jia-niang
      password:
        from_secret: GITEA_DOCKER_PUBLISH_TOKEN
      repo: gitea/jia-niang/cfda-api
      tags: latest
      registry: gitea
      purge: false
      mirror: https://docker.mirrors.sjtug.sjtu.edu.cn

  - name: stop-service
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - cd /root/project-config/cfda
        - docker compose down || true
        - docker rm gitea/jia-niang/cfda-api || true
        - docker image rm gitea/jia-niang/cfda-api:latest || true
  
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - cd /root/project-config/cfda
        - docker compose up -d

trigger:
  branch:
    - master
