kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build
    image: plugins/docker
    settings:
      username: paperplanecc
      password:
        from_secret: DOCKER_PASSWORD
      repo: paperplanecc/cfda-be
      tags: latest
      mirror: https://mirror.ccs.tencentyun.com
      registry: docker.io

  - name: stop-service
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - cd /root/project-config/cfda
        - docker compose down || true
        - docker rm paperplanecc/cfda-be || true
        - docker image rm paperplanecc/cfda-be:latest || true
  
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - cd /root/project-config/cfda
        - docker compose up -d

trigger:
  branch:
    - master
