version: '2'
services:
  node:
    container_name: cfda
    image: node:12
    user: ci
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - 9000
    ports:
      - 9000:9000
    command: npm run start
