version: '3'

networks:
  default-app:
    name: default-app
    external: true
  default-db-mongo:
    name: default-db-mongo
    external: true

services:
  cfda-be:
    container_name: cfda-be
    image: paperplanecc/cfda-be:latest
    restart: always
    networks:
      - default-app
      - default-db-mongo
